[project]
name = "funcit"
version = "0.0.1"
authors = [
    { name="Hudson Cooper", email="hncooper96@gmail.com" },
]
description = "Make code func"
dependencies = []

[project.urls]
source = "https://github.com/hudson-ai/funcit"
download = "https://pypi.org/project/funcit/#files"
